
project_id = "vaabpicspdbolvutnscp"

[functions.receive-partner-data]
verify_jwt = false

[functions.test-webhook-connection]
verify_jwt = false

[functions.export-sales-data]
verify_jwt = false

[functions.create-lead-from-fattura]
verify_jwt = false

[functions.send-delivery-term-webhook]
verify_jwt = false
