
-- Primeiro, vamos limpar a tabela leads existente para evitar duplicatas
DELETE FROM public.leads;

-- Inserir todos os 47 leads do CSV com dados normalizados
INSERT INTO public.leads (empresa, nome_cliente, link_blaster, data_ultimo_contato, link_chat, vendedor, situacao, observacoes) VALUES
('MAQSOLO FABRICAÇÃO', 'Marcelo', 'https://blaster.zipline.com.br/egestor/#415606', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#823814', 'Lilian', 'Esta formulando o que vai por no formulario', NULL),
('HFEadm', 'Debora', 'https://blaster.zipline.com.br/egestor/?#422492', '2025-06-30', 'https://zipline.zipticket.com.br/painel/#816631', NULL, 'Chamada pela terceira vez e ainda sem resposta', NULL),
('ESPAÇO VIVA BEM', 'Gabriela', 'https://blaster.zipline.com.br/egestor/?#422366', '2025-06-20', 'https://zipline.zipticket.com.br/painel/#816611', NULL, 'Esta reorganizando a empresa e esta esperando para mandar as fotos e formulario apos a conclusao', NULL),
('VIVIANE SAPIENZA CHRYSTAL BOTTGER', 'Viviane', NULL, '2025-07-01', NULL, 'Escobar', 'Cliente cancelou', NULL),
('Pernambuco Peças', 'Josenildo', 'https://blaster.zipline.com.br/egestor/?#406409', '2025-07-01', 'https://zipline.zipticket.com.br/zap/?820372', NULL, 'Chamado dia 08/07 de novo, pois tinha comentado que queria fazer algumas mudanças no site mas nao entrou em contato', NULL),
('JL CARROCERIAS', 'Sandy', 'https://blaster.zipline.com.br/egestor/?#339069', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#624191', NULL, 'Aguardando fotos da cliente, chamei dnv dia 08/07', NULL),
('EMMY STORE', 'Marido da Emmy', 'https://blaster.zipline.com.br/egestor/?#420860', '2025-06-30', 'https://zipline.zipticket.com.br/painel/#819282', NULL, 'Site quase pronto pois ela nao responde e nao passou mais informações', NULL),
('GNX COMERCIO', 'Talita', 'https://blaster.zipline.com.br/egestor/?#342998', '2025-06-30', 'https://zipline.zipticket.com.br/zap/?384315', NULL, 'Chamei pelo numero que o paulo indicou e nao obtive resposta ainda', NULL),
('DICERTO ACABAMENTOS', 'Edson', 'https://blaster.zipline.com.br/egestor/?#276613', '2025-06-30', 'https://zipline.zipticket.com.br/zap/?379608', NULL, 'Site finalizado e enviado ao cliente dia 08/07', NULL),
('LOJA ELETRONICOS', 'Otaviano', 'https://blaster.zipline.com.br/egestor/?#423874', '2025-06-24', 'https://zipline.zipticket.com.br/painel/#818303', NULL, 'Aguardando preencher formulario, dia 08/07 chamei novamente', NULL),
('GIDEAO MOVEIS', 'Gideao', 'https://blaster.zipline.com.br/egestor/#424639', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#821382', 'Escobar', 'Chamado novamente dia 08/07, aguardando resposta', NULL),
('GISYSTEM', 'Gilson', 'https://blaster.zipline.com.br/egestor/?#314544', '2025-06-27', 'https://zipline.zipticket.com.br/painel/#824267', NULL, 'Site pronto, so aguardando ele enviar as avaliacoes de clientes', NULL),
('SABOR DO CEU', 'Michele', 'https://blaster.zipline.com.br/egestor/#411276', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#814396', NULL, 'Site pronto, porem o cliente comentou sobre mudanças mas nunca mais retornou, chamado dia 08/07 dnv', NULL),
('GAJAHDIST', 'Athayde', 'https://blaster.zipline.com.br/egestor/?#423704', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#817660', 'Escobar', 'Aguardando preencher formulario / chamada novamente dia 08/07', NULL),
('STRONGERPECA', 'Angela', 'https://blaster.zipline.com.br/egestor/#420144', '2025-07-01', 'https://zipline.zipticket.com.br/zap/?811540', NULL, 'Aguardando preencher formulario / chamada dia 08/07 novamente', NULL),
('ROMILVO ANTONIO DE LIMA', 'Romilvo = Ricardo', 'https://blaster.zipline.com.br/egestor/#419932', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#826175', NULL, 'Aguardando resposta / chamado novamente dia 08/07', NULL),
('GisSystem', 'Gilson', 'https://blaster.zipline.com.br/egestor/?#314544', '2025-07-01', 'https://zipline.zipticket.com.br/zap/?824267', NULL, 'Chat adicional com cliente sobre o site', 'https://zipline.zipticket.com.br/zap/?824267'),
('RMBEAUTY', 'Victor', 'https://blaster.zipline.com.br/egestor/#426509', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#824525', NULL, 'Aguardando resposta / dia 08/07 configurando dominio', NULL),
('RRestofados', 'Rafael', NULL, '2025-07-01', NULL, NULL, 'Recebido form (incompleto pra caraca) / solicitado pelo wapp para mandar novamente mas ate dia 08/07 nada', 'Contato via WhatsApp'),
('DSScomercio', 'Diogo / Luiza', 'https://blaster.zipline.com.br/egestor/?#320793', '2025-07-01', NULL, 'Paulo', 'Vai responder entre hj e amanha (03/07) / 08/07 nada ainda', 'Contato via WhatsApp'),
('LOJAS DO BORRACHEIRO', 'Carlos / Bruna', 'https://blaster.zipline.com.br/egestor/?#301477', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#824963', 'Paulo', 'Aguardando resposta / configurando dominio 08/07', NULL),
('EVOLUCAO RODAS', 'Elizandra', 'https://blaster.zipline.com.br/nfemais/#101430', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#397697', 'Paulo', 'Site pronto', NULL),
('DIALEINN', 'Denise', 'https://blaster.zipline.com.br/egestor/#423172', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#828672', 'Larissa', 'Chamada dnv dia 08/07 aguardando preencher formulario', NULL),
('Melalimentos', 'Daniel', 'https://blaster.zipline.com.br/nfemais/#421623', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#824002', NULL, 'Aguardando resposta / 08/07 chamado novamente', NULL),
('HIPERGM MAIK E SOUZA ATACADAO', 'Gutemberg', 'https://blaster.zipline.com.br/nfemais/#415800', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#825394', 'Eduarda', 'Aguardando preenchimento do formulario / dia 08/07 chamado novamente', NULL),
('PLAY FOTOS', 'Francisco', 'https://blaster.zipline.com.br/egestor/?#427014', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#826162', 'Escobar', 'Aguardando resposta', NULL),
('FABIOLA VASCONCELOS', 'Fabiola', 'https://blaster.zipline.com.br/egestor/#427188', '2025-07-02', 'https://zipline.zipticket.com.br/zap/?520847', 'Escobar', 'Vai aguardar a abertura da empresa dela para fazer o site', NULL),
('JULIOBASSETTI', 'Julio', 'https://blaster.zipline.com.br/egestor/?#372276', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#824823', 'Parceiro', 'Montagem do site', NULL),
('SUPER BRINDE', 'Renato', 'https://blaster.zipline.com.br/nfemais/#412864', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#822182', 'Renata', 'Cancelamento do cliente', NULL),
('REDENCAO ARTES', 'Rodrigo', 'https://blaster.zipline.com.br/egestor/#427793', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#826267', 'Lilian', 'Aguardando resposta / chamado dia 08/07 aguardando resposta', NULL),
('DEMOOP', 'Mari', 'https://blaster.zipline.com.br/egestor/?#210440', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#104579', NULL, 'Site pronto, aguardando cliente caso queira mudanças dos 7 dias', NULL),
('DRSERVICOSSEGURANCA', 'Damiao', 'https://blaster.zipline.com.br/egestor/?#338254', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#828958', 'Escobar', 'Aguardando resposta', NULL),
('DENGRADI', 'Andre', 'https://blaster.zipline.com.br/egestor/#344286', '2025-07-04', 'https://zipline.zipticket.com.br/painel/#583842', 'Paulo', 'Dia 08/07 enviado o procedimento e aguardando o retorno do cliente', NULL),
('LP COMERCIAL DE CONFECCOES LTDA', 'Natali', 'https://blaster.zipline.com.br/nfemais/#397456', '2025-07-07', 'https://zipline.zipticket.com.br/painel/#640946', 'João', 'Enviado o procedimento, e aguardando o cliente preencher o formulario', NULL),
('ISOPORTERM', 'Marcella', 'https://blaster.zipline.com.br/egestor/#276281', '2025-07-07', 'https://zipline.zipticket.com.br/painel/#625208', 'Paulo', 'Aguardando o cliente preencher o formulario', NULL),
('Recuperacell', 'Diego', 'https://blaster.zipline.com.br/egestor/#427608', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#829134', 'Patricia', 'Aguardando resposta', NULL),
('NOBRECOMERCIO', 'Jenifer', 'https://blaster.zipline.com.br/egestor/#344549', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#348886', 'Paulo', 'Aguardando resposta', NULL),
('ZENER', 'Paulo', 'https://blaster.zipline.com.br/egestor/?#354558', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#634705', 'Escobar', 'Aguardando resposta', NULL),
('R-SOLVER', 'Gerson', 'https://blaster.zipline.com.br/egestor/#310178', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#473095', 'Paulo', 'Aguardando resposta', NULL),
('SPLASHCAR', 'Heloisa', 'https://blaster.zipline.com.br/egestor/#429584', '2025-07-10', 'https://zipline.zipticket.com.br/painel/#830707', 'Escobar', 'Aguardando resposta', NULL),
('TFFPECAS', 'Kleber', 'https://blaster.zipline.com.br/egestor/?#325142', '2025-07-10', 'https://zipline.zipticket.com.br/painel/#522623', 'Paulo', 'Aguardando resposta', NULL),
('FIGUEREDOEMPREENDIMENTOS', 'Rayssa', 'https://blaster.zipline.com.br/egestor/?#428093', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831137', 'Guilherme', 'Aguardando resposta', NULL),
('SAOJORGEAGROPECUARIA', 'Renata', 'https://blaster.zipline.com.br/egestor/?#429862', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831168', 'Lilian', 'Aguardando resposta', NULL),
('MEGADISELAUTOPECAS', 'Egiane', 'https://blaster.zipline.com.br/egestor/#425657', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831696', 'Guilherme', 'Aguardando resposta', NULL),
('LOTECH', 'Erika', 'https://blaster.zipline.com.br/egestor/#428045', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831464', 'Matheus', 'Aguardando resposta', NULL),
('MVMARIAVALENTINACOSMETICOS', 'Alana', 'https://blaster.zipline.com.br/egestor/?#426652', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831740', 'Patricia', 'Aguardando resposta', NULL),
('PHIMPORTSMATRIZ', 'Pedro', 'https://blaster.zipline.com.br/egestor/#286749', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#398135', 'Matheus', 'Aguardando resposta', NULL),
('OTICAS MAELU', 'Marcela', 'https://blaster.zipline.com.br/egestor/#335453', '2025-07-14', 'https://zipline.zipticket.com.br/painel/#555231', 'Escobar', 'Aguardando resposta', NULL),
('LOJAMUNDOENCANTADO', 'Lilian', 'https://blaster.zipline.com.br/egestor/?#224574', '2025-07-14', 'https://zipline.zipticket.com.br/painel/#832781', 'Escobar', 'Aguardando resposta', NULL);
