
-- Inserir todos os leads do CSV fornecido
INSERT INTO public.leads (empresa, nome_cliente, link_blaster, data_ultimo_contato, link_chat, vendedor, situacao, observacoes) VALUES
-- Leads já existentes (mantendo)
('MAQSOLO FABRICAÇÃO', 'Marcelo', 'https://blaster.zipline.com.br/egestor/#415606', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#823814', 'LILIAN', 'esta formulando o que vai por no formulario', NULL),
('HFEadm', 'Debora', 'https://blaster.zipline.com.br/egestor/?#422492', '2025-06-30', 'https://zipline.zipticket.com.br/painel/#816631', NULL, 'chamada pela terceira vez e ainda sem resposta', NULL),
('ESPAÇO VIVA BEM', 'Gabriela', 'https://blaster.zipline.com.br/egestor/?#422366', '2025-06-20', 'https://zipline.zipticket.com.br/painel/#816611', NULL, 'esta reorganizando a empresa e esta esperando para mandar as fotos e formulario apos a conclusao', NULL),

-- Novos leads do CSV
('VIVIANE SAPIENZA CHRYSTAL BOTTGER', 'Viviane', NULL, '2025-07-01', NULL, 'Escobar', 'cliente cancelou', NULL),
('pernambuco peças', 'Josenildo', 'https://blaster.zipline.com.br/egestor/?#406409', '2025-07-01', 'https://zipline.zipticket.com.br/zap/?820372', NULL, 'chamado dia 08/07 de novo, pois tinha comentado que queria fazer algumas mudanças no site mas nao entrou em contato', NULL),
('JL CARROCERIAS', 'Sandy', 'https://blaster.zipline.com.br/egestor/?#339069', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#624191', NULL, 'aguardando fotos da cliente, chamei dnv dia 08/07', NULL),
('EMMY STORE', 'MARIDO DA EMMY', 'https://blaster.zipline.com.br/egestor/?#420860', '2025-06-30', 'https://zipline.zipticket.com.br/painel/#819282', NULL, 'SITE QUASE PRONTO POIS ELA NAO RESPONDE E NAO PASSOU MAIS NFORMAÇOES', NULL),
('GNX COMERCIO', 'Talita', 'https://blaster.zipline.com.br/egestor/?#342998', '2025-06-30', 'https://zipline.zipticket.com.br/zap/?384315', NULL, 'chamei pelo numero que o paulo indicou e nao obtive resposta ainda', NULL),
('DICERTO ACABAMENTOS', 'Edson', 'https://blaster.zipline.com.br/egestor/?#276613', '2025-06-30', 'https://zipline.zipticket.com.br/zap/?379608', NULL, 'site finalizado e enviao ao cliente dia 08/07', NULL),
('LOJA ELETRONICOS', 'Otaviano', 'https://blaster.zipline.com.br/egestor/?#423874', '2025-06-24', 'https://zipline.zipticket.com.br/painel/#818303', NULL, 'aguardando preesncher formulario, dia 08/07 chamei novamente', NULL),
('GIDEAO MOVEIS', 'Gideao', 'https://blaster.zipline.com.br/egestor/#424639', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#821382', 'escobar', 'chamado novamente dia 08/07, aguaradando resposta', NULL),
('GISYSTEM', 'Gilson', 'https://blaster.zipline.com.br/egestor/?#314544', '2025-06-27', 'https://zipline.zipticket.com.br/painel/#824267', NULL, 'SITE PRONTO, SO AGUARDADNO ELE ENVIAR AS AVALIAÇOES DE CLIENTES', NULL),
('SABOR DO CEU', 'Michele', 'https://blaster.zipline.com.br/egestor/#411276', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#814396', NULL, 'site pronto, porem o cliente comentou sobre mudanças mas nunca mais retornou, chamado dia 08/07 dnv', NULL),
('GAJAHDIST', 'Athayde', 'https://blaster.zipline.com.br/egestor/?#423704', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#817660', 'escobar', 'aguardando preesncher formulario/ chamada novamente dia 08/07', NULL),
('STRONGERPECA', 'Angela', 'https://blaster.zipline.com.br/egestor/#420144', '2025-07-01', 'https://zipline.zipticket.com.br/zap/?811540', NULL, 'aguardando preencher formulario/ chamada dia 08/07 novamente', NULL),
('ROMILVO ANTONIO DE LIMA', 'Romilvo = Ricardo', 'https://blaster.zipline.com.br/egestor/#419932', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#826175', NULL, 'aguardando resposta/ chamado novamente dia 08/07', NULL),
('gisSystem', 'gilson', 'https://blaster.zipline.com.br/egestor/?#314544', '2025-07-01', 'https://zipline.zipticket.com.br/zap/?824267', NULL, 'https://zipline.zipticket.com.br/zap/?824267   esse é chat com quem estou falando sobre o site', NULL),
('RMBEAUTY', 'Victor', 'https://blaster.zipline.com.br/egestor/#426509', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#824525', NULL, 'aguardando resposta/ dia 08/07 configurando dominio', NULL),
('RRestofados', 'rafael  (WATS)', 'watswapp', '2025-07-01', NULL, NULL, 'recebido form (incompleto pra caraca)/ solicitado pelo wapp para mandar novamente mas ate dia 08/07 nada', NULL),
('DSScomercio', 'Diogo  (WATS)  Luiza (WATS)', 'https://blaster.zipline.com.br/egestor/?#320793', '2025-07-01', NULL, 'paulo', 'vai responder entre hj e amanha (03/07)/ 08/07 nada ainda', NULL),
('LOJAS DO BORRACHEIRO', 'Carlos-- Bruna', 'https://blaster.zipline.com.br/egestor/?#301477', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#824963', 'paulo', 'aguardando resposta/ configurando dominio 08/07', NULL),
('EVOLUÇAO RODAS', 'Elizandra', 'https://blaster.zipline.com.br/nfemais/#101430', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#397697', 'paulo', 'site pronto', NULL),
('DIALEINN', 'Denise', 'https://blaster.zipline.com.br/egestor/#423172', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#828672', 'Larissa', 'chamada dnv dia 08/07 aguardando preencher formulario', NULL),
('melalimentos', 'Daniel', 'https://blaster.zipline.com.br/nfemais/#421623', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#824002', NULL, 'aguardadno resposta/ 08/07 chamado novamente', NULL),
('HIPERGM maik e souza atacadao', 'Gutemberg', 'https://blaster.zipline.com.br/nfemais/#415800', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#825394', 'Eduarda', 'aguardando preeenchimento do formulario/ dia 08/07 chamado novamente', NULL),
('PLAY FOTOS', 'Francisco', 'https://blaster.zipline.com.br/egestor/?#427014', '2025-07-02', 'https://zipline.zipticket.com.br/painel/#826162', 'Escobar', 'aguardadno resposta', NULL),
('FABIOLA VASCONCELOS', 'Fabiola', 'https://blaster.zipline.com.br/egestor/#427188', '2025-07-02', 'https://zipline.zipticket.com.br/zap/?520847', 'Escobar', 'vai aguardar a abertuda da empresa dela para fazer o site', NULL),
('JULIOBASSETTI', 'Julio', 'https://blaster.zipline.com.br/egestor/?#372276', '2025-07-01', 'https://zipline.zipticket.com.br/painel/#824823', 'parceiro', 'montagem do site', NULL),
('SUPER BRINDE', 'Renato', 'https://blaster.zipline.com.br/nfemais/#412864', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#822182', 'Renata', 'cancelamento do cliente', NULL),
('REDENÇAO ARTES', 'Rodrigo', 'https://blaster.zipline.com.br/egestor/#427793', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#826267', 'lilian', 'aguardando resposta/ chamado dia 08/07 aguardando resposta', NULL),
('DEMOOP', 'Mari', 'https://blaster.zipline.com.br/egestor/?#210440', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#104579', NULL, 'site pronto, aguardando cliente caso quiera mudanças dos 7 dias', NULL),
('DRSERVIÇOSSEGURANÇA', 'Damiao', 'https://blaster.zipline.com.br/egestor/?#338254', '2025-07-03', 'https://zipline.zipticket.com.br/painel/#828958', 'Escobar', 'aguardadno resposta', NULL),
('DENGRADI', 'Andre', 'https://blaster.zipline.com.br/egestor/#344286', '2025-07-04', 'https://zipline.zipticket.com.br/painel/#583842', 'Paulo', 'dia 08/07 enviado o procedimento e aguardando o retorno do cliente', NULL),
('LP COMERCIAL DE CONFECCOES LTDA', 'Natali', 'https://blaster.zipline.com.br/nfemais/#397456', '2025-07-07', 'https://zipline.zipticket.com.br/painel/#640946', 'JOAO', 'enviado o procedimento, e aguardando o cliente preencher o formulario', NULL),
('ISOPORTERM', 'Marcella', 'https://blaster.zipline.com.br/egestor/#276281', '2025-07-07', 'https://zipline.zipticket.com.br/painel/#625208', 'Paulo', 'aguardando o cliente preencher o formulario', NULL),
('recuperacell', 'Diego', 'https://blaster.zipline.com.br/egestor/#427608', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#829134', 'Patricia', 'aguardando resposta', NULL),
('NOBRECOMERCIO', 'Jenifer', 'https://blaster.zipline.com.br/egestor/#344549', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#348886', 'Paulo', 'aguardando resposta', NULL),
('ZENER', 'Paulo', 'https://blaster.zipline.com.br/egestor/?#354558', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#634705', 'Escobar', 'aguardando resposta', NULL),
('R-SOLVER', 'Gerson', 'https://blaster.zipline.com.br/egestor/#310178', '2025-07-08', 'https://zipline.zipticket.com.br/painel/#473095', 'Paulo', 'aguardando resposta', NULL),
('SPLASHCAR', 'HELOISA', 'https://blaster.zipline.com.br/egestor/#429584', '2025-07-10', 'https://zipline.zipticket.com.br/painel/#830707', 'Escobar', 'aguardando resposta', NULL),
('TFFPECAS', 'Kleber', 'https://blaster.zipline.com.br/egestor/?#325142', '2025-07-10', 'https://zipline.zipticket.com.br/painel/#522623', 'Paulo', 'aguradando resposta', NULL),
('FIGUEREDOEMPREENDIMENTOS', 'Rayssa', 'https://blaster.zipline.com.br/egestor/?#428093', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831137', 'Guilherme', 'aguardando resposta', NULL),
('SAOJORGEAGROPECUARIA', 'Renata', 'https://blaster.zipline.com.br/egestor/?#429862', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831168', 'Lilian', 'aguardando resposta', NULL),
('MEGADISELAUTOPECAS', 'Egiane', 'https://blaster.zipline.com.br/egestor/#425657', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831696', 'Guilherme', 'aguardando resposta', NULL),
('LOTECH', 'Erika', 'https://blaster.zipline.com.br/egestor/#428045', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831464', 'Matheus', 'aguardando resposta', NULL),
('mvmariavalentinacosmeticos', 'Alana', 'https://blaster.zipline.com.br/egestor/?#426652', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#831740', 'Patricia', 'aguardando resposta', NULL),
('PHIMPORTSMATRIZ', 'Pedro', 'https://blaster.zipline.com.br/egestor/#286749', '2025-07-11', 'https://zipline.zipticket.com.br/painel/#398135', 'Matheus', 'aguardando resposta', NULL),
('OTICAS MAELU', 'Marcela', 'https://blaster.zipline.com.br/egestor/#335453', '2025-07-14', 'https://zipline.zipticket.com.br/painel/#555231', 'Escobar', 'aguardadno resposta', NULL),
('LOJAMUNDOENCANTADO', 'Lilian', 'https://blaster.zipline.com.br/egestor/?#224574', '2025-07-14', 'https://zipline.zipticket.com.br/painel/#832781', 'Escobar', 'aguardando resposta', NULL)

ON CONFLICT (empresa, nome_cliente) DO NOTHING;
